// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSWf806dUGzXniYAACX282yjmgSYHEBV8',
    appId: '1:130796918978:web:87bbfbdc4476c079d0035b',
    messagingSenderId: '130796918978',
    projectId: 'straydog-catcher',
    authDomain: 'straydog-catcher.firebaseapp.com',
    storageBucket: 'straydog-catcher.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlN9BGcrVluwzS83CMin7CnLF-CfYDu5s',
    appId: '1:130796918978:android:587ec02be27a305cd0035b',
    messagingSenderId: '130796918978',
    projectId: 'straydog-catcher',
    storageBucket: 'straydog-catcher.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcn0RmKoR5A8zRy3zFQvic9YiXkk6Gu4k',
    appId: '1:130796918978:ios:14b609e571a42c1fd0035b',
    messagingSenderId: '130796918978',
    projectId: 'straydog-catcher',
    storageBucket: 'straydog-catcher.appspot.com',
    iosBundleId: 'com.example.dogCatcher',
  );
}
